### ISSUE TITLE
Refactoring Supervisor

### ISSUE THREAD

**Issue by zealousduck** [zealousduck/AUPhotoUpload#20]
Supervisor's run method is currently disgusting, and is only likely to get worse with the InternetPatch. It's nearly 100 lines long, so we really need to refactor that into lots of separate methods. Off the top of my head, I can think of:
- Initialize image directory (if necessary)
- Initialize internet status
- Initial scan of camera image list
- Handle GUI job
- Check handler queue
- Check internet connection

These don't have to be the names, but hey! It's a start.

**Comment by emseduau** [comment]
Made a new branch I'll be working in, so far I have a few of these knocked out, I'll work on the rest soon.

**Comment by emseduau** [comment]
I've completed refactoring it for now. Let me know if there are any issues with these changes. I believe I've preserved the same behavior.

**Comment by zealousduck** [comment]
These things are pretty much done per the Candidate1 merge from EvanCycle3.
